[git_status]
conflicted = "ConflictğŸ’€"
ahead = "aheadğŸğŸ’¨"
behind = "behindğŸ˜°"
diverged = "divergedğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "ğŸ—‚ï¸"
renamed = "âœï¸"
deleted = "ğŸ—‘"

[kubernetes]
format = 'on [â›µ ($user)|($cluster)|$context\($namespace\)](dimmed 213) '
disabled = false
detect_files = ['k8s']

[gcloud]
disabled = true
