[git_status]
conflicted = "ConflictğŸ’€"
ahead = "ahedğŸğŸ’¨"
behind = "behindğŸ˜°"
diverged = "divergedğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "ğŸ—‚ï¸"
renamed = "âœï¸"
deleted = "ğŸ—‘"
